[package]
name = "firework-communicator"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
firework-common = {path = "../firework-common"}

async-std = "1.9.0"
bytes = "*"
num-traits = "0.2.14"
uuid = "*"
